#################################### Aruba Switch ###############################################

- hostname: Aruba-2930F
  device_type: aruba_os
  host: 10.1.1.1
  directory: /home/backup/A/
  
- hostname: Aruba-2930F
  device_type: aruba_os
  host: 10.1.1.2
  directory: /home/backup/A/

- hostname: Aruba-6200F
  device_type: aruba_os
  host: 10.1.1.3
  directory: /home/backup/B/

- hostname: Aruba-8320
  device_type: aruba_os
  host: 10.1.1.250
  directory: /home/backup/A/


#################################### Cisco Switch ############################################

- hostname: Cisco-2960S
  device_type: cisco_ios
  host: 10.1.2.1
  directory: /home/backup/A/

##################################### HPE  Switch #############################################

- hostname: HPE-5120
  device_type: hp_comware
  host: 10.2.2.1
  directory: /home/backup/A/

- hostname: HPE-5130-SRV
  device_type: hp_comware
  host: 10.2.2.2
  directory: /home/backup/A/

- hostname: HPE-1950
  device_type: hp_comware
  host: 10.2.2.4
  directory: /home/backup/A/

###################################### Supermicro ###################################
- hostname: SSE-X24S-SSE
  device_type: supermicro_smis_telnet
  host: 10.5.5.1
  directory:  /home/backup/A/
